#pragma config(Sensor, in1,    RightLF,        sensorLineFollower)
#pragma config(Sensor, in2,    CenterLF,       sensorLineFollower)
#pragma config(Sensor, in3,    LeftLF,         sensorLineFollower)
#pragma config(Sensor, in4,    LightSensor,    sensorReflection)
#pragma config(Sensor, in5,    ArmStatus,      sensorPotentiometer)
#pragma config(Sensor, dgtl4,  Bumper,         sensorTouch)
#pragma config(Sensor, dgtl5,  LimitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl7,  Sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl9,  IncoderL,       sensorQuadEncoder)
#pragma config(Sensor, dgtl11, IncoderR,       sensorQuadEncoder)
#pragma config(Motor,  port2,           LeftMotor,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           Claw,          tmotorVex269, openLoop)
#pragma config(Motor,  port8,           Arm,           tmotorVex269, openLoop)
#pragma config(Motor,  port9,           RightMotor,    tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Clawbot.h"
int threshold = 1000;
int workOnYourOwn = 1;

task myMain()
{
	while(true)
	{
		SensorValue[RightLF] > threshold
	}
}

task options()
{
	if(vexRT[Btn7R]==true)
	{
		threshold+=100;
	}
	if(vexRT[Btn7L]==true)
	{
		threshold-=100;
	}
	if(vexRT[Btn7U]==true)
	{
		workOnYourOwn=1;
		StopTask(remoteControlle);
		StartTask(myMain);
	}
	if(vexRT[Btn7D]==true)//controller takes controll
	{
		workOnYourOwn=0;
		StartTask(remoteControlle);
		StopTask(myMain);
	}
}


task main()
{
	StartTask(myMain);//run the program
	StartTask(options);

	while(vexRT[Btn8D]!=true&&Bumper!=true){}//don't stop untill we say so

	StopAllTasks();//stop everything!
}








task remoteControlle()
{
	if(abs(vexRT[Ch3])>20)
		{
			motor[LeftMotor]  = vexRT[Ch3];
		}
		else{motor[LeftMotor]=0;}

		if(abs(vexRT[Ch2])>20)
		{
			motor[RightMotor] = vexRT[Ch2];
		}
		else {motor[RightMotor]=0;}
		/*motor[LeftMotor]  = (vexRT[Ch2] + vexRT[Ch1])/2;
		motor[RightMotor] = (vexRT[Ch2] - vexRT[Ch1])/2;*/

		if(vexRT[Btn5U] == 1)
		{
			motor[Arm] = -127;
		}
		else if(vexRT[Btn5D] == 1)
		{
			if(SensorValue[LimitSwitch]==0)
			{
				motor[Arm] = 127;
			}
		}
		else
		{
			motor[Arm] = 0;
		}

		if(vexRT[Btn6U] == 1)
		{
			motor[Claw] = -127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[Claw] = 127;
		}
		else
		{
			motor[Claw] = 0;
		}
	}
