#pragma config(Sensor, in1,    RightLF,        sensorLineFollower)
#pragma config(Sensor, in2,    CenterLF,       sensorLineFollower)
#pragma config(Sensor, in3,    LeftLF,         sensorLineFollower)
#pragma config(Sensor, in4,    LightSensor,    sensorReflection)
#pragma config(Sensor, in5,    ArmStatus,      sensorPotentiometer)
#pragma config(Sensor, in7,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl4,  Bumper,         sensorTouch)
#pragma config(Sensor, dgtl5,  LimitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl7,  Sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl9,  IncoderL,       sensorQuadEncoder)
#pragma config(Sensor, dgtl11, IncoderR,       sensorQuadEncoder)
#pragma config(Motor,  port2,           LeftMotor,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           Claw,          tmotorVex269, openLoop)
#pragma config(Motor,  port8,           Arm,           tmotorVex269, openLoop)
#pragma config(Motor,  port9,           RightMotor,    tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Gyro Based Turns - Basic
-This program instructs your robot to turn for the specified number of degrees in "degrees10".
-For best sensor results, clear out the gyro and manually configure it at the begging of the code.
-The Gyro is configured by default to provide values from 0 to -3600 for clockwise rotation,
 and 0 to 3600 for counter-clockwise rotation
Robot Model(s): Swervebot
[I/O Port]          [Name]              [Type]                [Description]
Motor Port 2        rightMotor          VEX Motor             Right side motor
Motor Port 3        leftMotor           VEX Motor             Left side motor
Analog Port 8       in8                 VEX Gyro              Top-center mounted,
                                                              away from the Cortex
----------------------------------------------------------------------------------------------------*/
int gildi=0;
int goal = 0;
/*
float Mathing = 0;
float motors[]={0,0};*/
void turn_giro(int degrees10,bool counterclock){
	//Completely clear out any previous sensor readings by setting the port to "sensorNone"
	int last = -10;
	int setSpeed = 50;
	goal=degrees10;
	SensorType[gyro] = sensorNone;
  wait1Msec(1000);
  float SlowDown = 1;
  //Reconfigure Analog Port 7 as a Gyro sensor and allow time for ROBOTC to calibrate it
  SensorType[gyro] = sensorGyro;
  wait1Msec(2000);
  while(abs(SensorValue[gyro]) < degrees10)
  {
  	gildi = abs(SensorValue[gyro]);
  	if(degrees10<abs(SensorValue[gyro])+100)
  	{
  		SlowDown = 0.75;
  	}
		if (counterclock){
		motor[RightMotor] = setSpeed*SlowDown;
		motor[LeftMotor] = -setSpeed*SlowDown;
		}
		else{
		motor[RightMotor] = -setSpeed*SlowDown;
		motor[LeftMotor] = setSpeed*SlowDown;
		}
  }
  motor[RightMotor] = 0;
	motor[LeftMotor] = 0;
}


task main()
{
	turn_giro(1800,false);
}
